### PR TITLE
feat: add hands, head & heart one pager

### LINKED ISSUE #19: Describe *Hands, Head & Heart* in a One-Pager for students to use
## Background

We want to create and publish our first mental models on GitHub Pages to validate our hypothesis that the way we're approaching it - publicly on the web, easy language, one-pager format will help other students 
(and ourself) to start with their first (work related) projects.

## Acceptance Critera

* The mental model is explained in our adapted one-pager format
* It contains text and an explaining image
* It's in our GitHub project
* At least one content-wise review cycle is done within the team
* It's published on GitHub Pages

## Implementation Hints

* Dependency to adapted one-pager format (issue)

## Sources

* [3C-model](https://en.wikipedia.org/wiki/3C-model)
* [Collaboration Begins with You](https://www.leadershipnow.com/leadingblog/2015/10/collaboration_begins_with_you.html)

### PR DESCRIPTION
**Pull request by Claiyc**
This adds a markdown one pager containing info about the hands, head, heart mental model.

closes #19

### CODE REVIEW

**Review by XSnelliusX — APPROVED** [review]
Looks great!

**Review by MichaelMGraf — APPROVED** [review]
Perfect!

**Comment by jens1o** [comment]
I don't like it, I love it. ;)

**Review by jens1o — APPROVED** [review]

**Comment by 2000eBe** [comment]
Nice indeed!

**Pull request merged**
