### PR TITLE
feat(mentalModel): Introducing the Johari window model

### LINKED ISSUE #59: Describe the Johari Window
## Background

Coming into routine. Properly written one-pagers with consistent structure, correctly licensed are the next step to build a kick-ass mental models site.

This mental model is part of the Systems Thinking mental models.

## Implementation Hints

* Please consider #68 and #13 for the implementation.
* Find more and better sources and make sure to extract the pure essence.
* What is it that the reader should read, expects? What is it that we want the reader to understand?

## Sources

[thomykay: Johari Window](https://github.com/thomykay/devspace-systemsthinking/blob/e73a99affd710d197acfdfa2ad2d18871395ffad/src/material/mentalmodels.johari.md)

### PR DESCRIPTION
**Pull request by jens1o**
fixes #59

### CODE REVIEW

**Review by XSnelliusX — CHANGES_REQUESTED** [review]
add model to Readme.md missing

**Review by 2000eBe — APPROVED** [review]
Well done

**Comment by jens1o** [comment]
> Well done

you did all the work... don't praise yourself :P

**Comment by 2000eBe** [comment]
> > Well done
> 
> you did all the work... don't praise yourself :P

psst....

**Pull request merged**
