### PR TITLE
feat: Iceberg Model added #58

### LINKED ISSUE #58: Describe the Iceberg Model
## Background

Coming into routine. Properly written one-pagers with consistent structure, correctly licensed are the next step to build a kick-ass mental models site.

This mental model is part of the Systems Thinking mental models.

## Implementation Hints

* Please consider #68 and #13 for the implementation.
* Find more and better sources and make sure to extract the pure essence.
* What is it that the reader should read, expects? What is it that we want the reader to understand?

## Sources

[thomykay: Iceberg Model](https://github.com/thomykay/devspace-systemsthinking/blob/e73a99affd710d197acfdfa2ad2d18871395ffad/src/material/mentalmodels.iceberg.md)

### PR DESCRIPTION
**Pull request by MichaelMGraf**
Iceberg Model added.
everything is stolen! But noone knows!!!

fixes #58

### CODE REVIEW

**Review by Claiyc — APPROVED** [review]
Looking good

**Review by jens1o — CHANGES_REQUESTED** [review]
No, it is actually 0/10 because it is unuseable. Sorry dear team members, please take a look at the file extension (_if there is any supposedly_) whether everything works as intended. ;)

**Review by Claiyc — CHANGES_REQUESTED** [review]
Please also add a link to this mental model in index.md

**Comment by jens1o** [comment]
Good pointer, Timo! Also, the README should also be kept in mind to include a link. :)

**Review by Claiyc — APPROVED** [review]
Approving this for now, however links in README.md may be refactored in order to use relative paths (and sone links are missing anyway)

**Review by jens1o — APPROVED** [review]
lgtm as well.

Thank you for implementing the changes :)

**Comment by jens1o** [comment]
3 reviews, going to merge this …

**Pull request merged**
